module.exports={
    DOMAIN:'http://localhost:3000',
    MONGOURI:"mongodb+srv://root:root@cluster0.2zn2m.mongodb.net/kebajikan_app?retryWrites=true&w=majority",
    JWT_SECRET_ACCESS:"=Ylb1Llpg3e1hnYsluyNaJ2Fkdsd2gjn9C9Au54cHTZg",
    JWT_SECRET_REFRESH:"=Ylb1Llpg3e1hnYsluyNaJ2Fkdsd2gjn9C9Au54cHTZg",
    STRIPE_SECRET:"sk_test_51KRvhoFSMJYMwhaRZzuVJcdqi8JQjo5YPXcQAWCdb7XNvJZA4PdPDncEsLKfmclOmTQrUy0zh5k7rlUKxNn2RPZY00SR4cQ5pJ",
    NODEMAILER_EMAIL:"kebajikanapp@gmail.com",
    NODEMAILER_PASSWORD:"daefulhitydchyfd"
}