module.exports={
    DOMAIN:'http://localhost:3000',
    MONGOURI:"mongodb+srv://root:root@cluster0.2zn2m.mongodb.net/kebajikan_app?retryWrites=true&w=majority",
    JWT_SECRET_ACCESS:"=Ylb1Llpg3e1hnYsluyNaJ2Fkdsd2gjn9C9Au54cHTZg",
    JWT_SECRET_REFRESH:"=Ylb1Llpg3e1hnYsluyNaJ2Fkdsd2gjn9C9Au54cHTZg",
    STRIPE_SECRET:"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",
    NODEMAILER_EMAIL:"kebajikanapp@gmail.com",
    NODEMAILER_PASSWORD:"daefulhitydchyfd"
}