const mongoose = require('mongoose');
const {ObjectId} = mongoose.Schema.Types;

const charityApplicationSchema = new mongoose.Schema({
    event_id:{
        type:ObjectId,
        ref:"CharityEvent",
        required:true
    },
    name:{
        type:String,
        required:true
    },
    phone_number:{
        type:String,
        required:true
    },
    identity_no:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    ic_no:{
        type:String,
        required:true
    },
    marital_status:{
        type:String,
        required:true
    },
    current_address:{
        type:String,
        required:true
    },
    permanent_address:{
        type:String,
        required:true
    },
    program:{
        type:String,
        required:true
    },
    department:{
        type:String,
        required:true
    },
    year_of_study:{
        type:Number,
        required:true
    },
    semester:{
        type:Number,
        required:true
    },
    father_occ:{
        type:String,
        required:true
    },
    mother_occ:{
        type:String,
        required:true
    },
    father_income:{
        type:Number,
        required:true
    },
    mother_income:{
        type:Number,
        required:true
    },
    total_income:{
        type:Number,
        required:true
    },
    no_sibling:{
        type:Number,
        required:true
    },
    no_dependent:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        required:true,
        default:"Pending"
    },
    created_by:{
        type:ObjectId,
        ref:"User",
        required:true
    },
    created_on:{
        type:Date,
        default:Date.now,
        required:true
    },
    verified_by:{
        type:ObjectId
    },
    verified_on:{
        type:Date
    },
    document:{
        type:Object,
        required:true
    },
    photo:{
        type:Object,
        required:true
    }
})

mongoose.model('CharityApplication',charityApplicationSchema);